### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by suyogbargule** [anil2k/YOLOv5-DeepSort-Object-Tracking-PyTorch#2]
> python3 yolov5/detect_track.py --weights yolov5m.pt  --img 640  --source video.mp4  --save-txt --class 0 --line-thickness 1

Error :

detect_track: weights=['yolov5m.pt'], source=video.mp4, data=yolov5/data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5/runs/detect, name=exp, exist_ok=False, line_thickness=1, hide_labels=False, hide_conf=False, half=False, dnn=False, config_deepsort=deep_sort_pytorch/configs/deep_sort.yaml
Traceback (most recent call last):
  File "yolov5/detect_track.py", line 315, in <module>
    main(opt)
  File "yolov5/detect_track.py", line 310, in main
    run(**vars(opt))
  File "/home/suyog/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "yolov5/detect_track.py", line 95, in run
    cfg.merge_from_file(opt.config_deepsort)
  File "/home/suyog/Downloads/SSD/YOLOv5-DeepSort-Object-Tracking-PyTorch-main/yolov5/deep_sort_pytorch/utils/parser.py
line 23, in merge_from_file
    with open(config_file, 'r') as fo:
**FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/configs/deep_sort.yaml

**Comment by anil2k** [comment]
> > python3 yolov5/detect_track.py --weights yolov5m.pt  --img 640  --source video.mp4  --save-txt --class 0 --line-thickness 1
> 
> Error :
> 
> detect_track: weights=['yolov5m.pt'], source=video.mp4, data=yolov5/data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=True, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5/runs/detect, name=exp, exist_ok=False, line_thickness=1, hide_labels=False, hide_conf=False, half=False, dnn=False, config_deepsort=deep_sort_pytorch/configs/deep_sort.yaml Traceback (most recent call last): File "yolov5/detect_track.py", line 315, in main(opt) File "yolov5/detect_track.py", line 310, in main run(**vars(opt)) File "/home/suyog/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "yolov5/detect_track.py", line 95, in run cfg.merge_from_file(opt.config_deepsort) File "/home/suyog/Downloads/SSD/YOLOv5-DeepSort-Object-Tracking-PyTorch-main/yolov5/deep_sort_pytorch/utils/parser.py line 23, in merge_from_file with open(config_file, 'r') as fo: **FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/configs/deep_sort.yaml

Please check pyyaml version. !pip install pyyaml==5.4.1 and set current working directory  /home/suyog/Downloads/SSD/YOLOv5-DeepSort-Object-Tracking-PyTorch-main/yolov5/

**Comment by quinxg** [comment]
Error:

weights=yolov5\yolov5s.pt, source=0, data=yolov5\data\coco128.yaml, imgsz=[320, 320], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=yolov5\runs\detect, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, half=False, dnn=False, config_deepsort=E:/yolo-deepshort/yolov5/deep_sort_pytorch/configs/deep_sort.yaml
e:\yolo-deepshort\yolov5\deep_sort_pytorch\utils\parser.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
Traceback (most recent call last):
  File "e:\yolo-deepshort\yolov5\detect_track.py", line 317, in <module>
    main(opt)
  File "e:\yolo-deepshort\yolov5\detect_track.py", line 312, in main    
    run(**vars(opt))
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "e:\yolo-deepshort\yolov5\detect_track.py", line 96, in run
    deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
  File "e:\yolo-deepshort\yolov5\deep_sort_pytorch\deep_sort\deep_sort.py", line 18, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "e:\yolo-deepshort\yolov5\deep_sort_pytorch\deep_sort\deep\feature_extractor.py", line 14, in __init__
    state_dict = torch.load(model_path, map_location=torch.device(self.device))[
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'
